---

- name: create app dir
  file:
    state: directory
    path: "{{ app_dir }}"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"


- name: automatically cd into app dir on login
  lineinfile:
    dest: "/home/{{ app_user }}/.profile"
    line: "cd {{ app_dir }}"


- name: install pip packages
  pip:
    requirements: "{{ app_dir }}/requirements.txt"
    executable: "{{ venv_dir }}/bin/pip"


- name: generate settings file
  tags: settings
  template:
    src: settings.py.j2
    dest: "{{ app_dir }}/pytaku/settings.py"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: 0644
