# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='thumb_url',
            field=models.URLField(default=''),
        ),
    ]
